### ISSUE TITLE
export tool hangs with workbench 6.2

### ISSUE THREAD

**Issue by srdgame** [tatsushid/mysql-wb-exportsqlite#1]
OS: Debian SID
Workbench: v6.2.3.12312

Install this export plugin, go to 'Tools->Catalog->Export SQLite CREATE script'. Then workbench hangs, and takes 100% cpu usage.

**Comment by tatsushid** [comment]
It seems to go into a something infinite loop. I suspect `order_tables` causes that but to investigate it, I need an example schema. Can you provide me with the schema you try to export?

**Comment by srdgame** [comment]
I have upload my mwb file to:

http://pan.baidu.com/s/1c0wHGx6

**Comment by tatsushid** [comment]
Thanks for uploading the file! I confirmed it reproduced the issue on my environment too. I'll investigate it

**Comment by tatsushid** [comment]
I fixed the issue. Now I can export your mwb. Please try

**Comment by srdgame** [comment]
It says:

Error during "Export SQLite CREATE script"

error calling Python module function ExportSQLite.exportSQLite

**Comment by tatsushid** [comment]
This works well in my environment. How do you import the fixed plugin? I did by a following way
1. Open MySQL Workbench application
2. Open "Scripting" menu and "Install Plugin/Module..."
3. Open plugin file (in this case, `export_sqlite_grt.py`)
4. Choose "Replace" in a dialog box
5. Quit MySQL Workbench application and reopen it
6. Open a model file and try to export

**Comment by srdgame** [comment]
I have removed the plugin from 'scripting => plugin manager', And then "Scripting=>Install Plugin/Module".

**Comment by srdgame** [comment]
Following are the error logs:

16:20:29 [ERR][         python]: error calling ExportSQLite.exportSQLiteTraceback (most recent call last):
16:20:29 [ERR][         python]: Traceback (most recent call last):
16:20:29 [DB1][            grt]:   File "/home/cch/.mysql/workbench/modules/export_sqlite_grt.py", line 468, in exportSQLite
16:20:29 [ERR][         python]:   File "/home/cch/.mysql/workbench/modules/export_sqlite_grt.py", line 468, in exportSQLite
16:20:29 [DB1][            grt]:         wizard.run(True)
16:20:29 [ERR][         python]: wizard.run(True)
16:20:29 [DB1][            grt]: TypeErrorTypeError: : run() takes exactly 1 argument (2 given)run() takes exactly 1 argument (2 given)
16:20:29 [ERR][         python]: 
16:20:29 [ERR][            grt]: Error executing plugin wb.util.exportSQLite: error calling Python module function ExportSQLite.exportSQLite  
16:20:29 [DB2][            grt]: wb.util.exportSQLite finished in 0.03s
16:20:29 [ERR][      WBContext]: error calling Python module function ExportSQLite.exportSQLite

**Comment by srdgame** [comment]
![unnamed qq screenshot20150720162413](https://cloud.githubusercontent.com/assets/54447/8772127/c8ce9aee-2efb-11e5-88e3-b45b10b608bf.png)

**Comment by srdgame** [comment]
mysql-workbench  --version
*\* Message: Gnome keyring daemon seems to not be available. Stored passwords will be lost once quit
MySQL Workbench CE (GPL) 6.2.3 12312  build 2280

**Comment by tatsushid** [comment]
Thanks for reporting the details. It seems to be caused by `wizard.run(True)` at https://github.com/tatsushid/mysql-wb-exportsqlite/blob/e1731dc02699c1a245c4a943b67f69552d1e3c2d/export_sqlite_grt.py#L468 so I simply removed `True` from it. Please try the latest one
